<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$mediaInput = $form->get('o:thumbnail[o:id]');
$altLabelInput = $form->get('alt_label');
$headingInput = $form->get('home_heading');
$descriptionInput = $form->get('description');
$form->prepare();
?>
<div class="sidebar" id="page-options">
  <a href="#" class="sidebar-close o-icon-close"><span class="screen-reader-text"><?php echo $translate('Close'); ?></span></a>
  <div class="sidebar-content">
    <h3><?php echo $translate('Page Options'); ?></h3>
    <?php echo $this->formRow($mediaInput); ?>
    <div class="alt-label">
      <h3><?php echo $translate('Alternative Link Label'); ?></h3>
      <?php echo $this->formRow($altLabelInput); ?>
    </div>
    <div class="home-heading">
      <h3><?php echo $translate('Home Heading'); ?></h3>
      <?php echo $this->formRow($headingInput); ?>
    </div>
    <div class="description">
      <h3><?php echo $translate('Description'); ?></h3>
      <?php echo $this->formRow($descriptionInput); ?>
    </div>
  </div>

  <div id="page-options-confirm-panel" class="confirm-panel">
    <button><?php echo $translate('Apply changes'); ?></button>
  </div>
</div>